language: cpp

matrix:
  include:
    - name: "Linux (gcc)" 
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      services:
        - docker
      env: 
        - CMAKE_BUILD_TYPE: Release 
        - QT_PPA: beineri/opt-qt562-trusty
        - QT_VER: 56
    - name: "macOS (xcode 9.4)"
      os: osx
      osx_image: xcode9.4
      env: 
        - CMAKE_BUILD_TYPE: Release
    - name: Windows (VS2017 Win32)
      os: windows
      env:
        - PLATFORM: Win32
        - CMAKE_BUILD_TYPE: Release
        - QT5_BASE_DIR: "'/c/Qt/5.12.3/msvc2017'"
        - MSBUILD_PATH: "'/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin'"
    - name: Windows (VS2017 x64)
      os: windows
      env:
        - PLATFORM: x64
        - CMAKE_BUILD_TYPE: Release 
        - QT5_BASE_DIR: "'/c/Qt/5.12.3/msvc2017_64'"
        - MSBUILD_PATH: "'/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin'"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:$QT_PPA ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ;fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=$PATH:${QT5_BASE_DIR}/bin:${MSBUILD_PATH} ;fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get install -y git cmake python2.7-dev python3-dev python3-crypto libquazip-dev zlib1g-dev libpythonqt-dev libx11-dev mesa-common-dev libqt4-dev qtmobility-dev;
      sudo apt-get install -y qt${QT_VER}-meta-minimal qt${QT_VER}declarative qt${QT_VER}imageformats qt${QT_VER}multimedia qt${QT_VER}tools qt${QT_VER}svg qt${QT_VER}x11extras qt${QT_VER}xmlpatterns;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      brew install qt quazip;
      export PATH="$(brew --prefix qt)/bin:$PATH";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cinst -y --no-progress python3;
      export PATH="$(powershell -Command '("Process", "Machine" | % {
        [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", ""
      } | Select -Unique | % { cygpath $_ }) -Join ":"')";
      echo "PATH=$PATH";
      tools/travis-install-qt-windows.sh;
      wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.9.2.tar.gz;
      7z x libressl-2.9.2.tar.gz && 7z x libressl-2.9.2.tar;
      cd libressl-2.9.2;
      cmake . -DCMAKE_INSTALL_PREFIX=$(pwd) -DBUILD_OBJECT_LIBRARY_ONLY=OFF;
      cmake --build . --config $CMAKE_BUILD_TYPE --target install;
      export OPENSSL_ROOT_DIR=$(pwd);
      cd ..;
      wget http://www.zlib.net/zlib1211.zip;
      unzip zlib1211.zip;
      cd zlib-1.2.11;
      cmake . -DCMAKE_INSTALL_PREFIX=$(pwd);
      cmake --build . --config $CMAKE_BUILD_TYPE --target install;
      export ZLIB_BASE_DIR=$(pwd);
      cd ..;
      wget https://downloads.sourceforge.net/project/quazip/quazip/0.7.3/quazip-0.7.3.zip;
      unzip quazip-0.7.3.zip;
      cd quazip-0.7.3;
      sed -i '/ZLIB_LIBRARIES ""/d' ./CMakeLists.txt;
      cmake . -DCMAKE_INSTALL_PREFIX=$(pwd) -DCMAKE_PREFIX_PATH=${QT5_BASE_DIR}/lib/cmake -DZLIB_INCLUDE_DIRS=${ZLIB_BASE_DIR} -DZLIB_LIBRARIES=${ZLIB_BASE_DIR}/Release/zlib.lib;
      cmake --build . --config $CMAKE_BUILD_TYPE --target install;
      export QUAZIP_BASE_DIR=$(pwd);
      cd ..;
    fi

before_script:
  - mkdir build-qt5 build-qt4

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      cd build-qt4;
      cmake .. -DQT_USE_QT5=OFF -DPYTHON_USE_PYTHON3=OFF;
      make;
      cd ..;
      sudo apt-get purge -y libpythonqt-dev libpythonqt2.1 libquazip-dev libquazip0;
      source /opt/qt${QT_VER}/bin/qt${QT_VER}-env.sh;
    fi
  - cd build-qt5
  - git clone https://github.com/Orochimarufan/PythonQt
  - cd PythonQt
  - git checkout 18d4c24
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake . -DCMAKE_INSTALL_PREFIX=/usr -DPythonQt_Python3=ON -DPYTHONQT_WITH_WEBKIT=OFF -DBUILD_SHARED_LIBS=ON;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sudo cp -r /usr/include/python2.7 ./pythonincludes;
      sudo chmod 777 ./pythonincludes;
      curl https://trac.macports.org/raw-attachment/ticket/44288/patch-Include-pyport.h.diff | patch ./pythonincludes/pyport.h;
      cmake . -DCMAKE_PREFIX_PATH="$(brew --prefix qt)" -DPYTHON_INCLUDE_DIR=./pythonincludes -DPythonQt_Python3=OFF -DPYTHONQT_WITH_WEBKIT=OFF -DBUILD_SHARED_LIBS=ON;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake . -DCMAKE_INSTALL_PREFIX=$(pwd) -DPythonQt_Python3=ON -DPYTHONQT_WITH_WEBKIT=OFF -DBUILD_SHARED_LIBS=ON;
    fi
  - cmake --build . --config $CMAKE_BUILD_TYPE --target install
  - export PYTHONQT_BASE_DIR=$(pwd)
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      git clone https://github.com/stachenov/quazip;
      cd quazip;
      qmake PREFIX=/usr;
      sudo make install;
      cd ..;
      sudo ln -s /usr/lib/libQt5Python34_QtAll.so /usr/lib/libQtPython_QtAll.so;
      sudo ln -s /usr/lib/libQt5Python34.so /usr/lib/libQtPython.so;
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DPYTHONQT_INCLUDE_DIR=/usr/include/Qt5Python34/PythonQt/ -DPYTHONQT_QTALL_INCLUDE_DIR=/usr/include/Qt5Python34/PythonQt;
      make;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake ..  -DCMAKE_PREFIX_PATH="$(brew --prefix qt)" -DPYTHON_USE_PYTHON3=OFF -DPYTHON_INCLUDE_DIR=./PythonQt/build/pythonincludes -DPYTHONQT_LIBRARY=/usr/local/lib/libQt5Python27.dylib -DPYTHONQT_INCLUDE_DIR=/usr/local/include/Qt5Python27/PythonQt -DPYTHONQT_QTALL_LIBRARY=/usr/local/lib/libQt5Python27_QtAll.dylib -DPYTHONQT_QTALL_INCLUDE_DIR=/usr/local/include/Qt5Python27/PythonQt;
      make;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake ..  -DCMAKE_PREFIX_PATH=${QT5_BASE_DIR}/lib/cmake -DZLIB_INCLUDE_DIRS=${ZLIB_BASE_DIR} -DQUAZIP_INCLUDE_DIR=${QUAZIP_BASE_DIR}/include/quazip5 -DQUAZIP_LIBRARY=${QUAZIP_BASE_DIR}/lib/quazip5.lib -DPYTHONQT_INCLUDE_DIR=${PYTHONQT_BASE_DIR}/src -DPYTHONQT_LIBRARY=${PYTHONQT_BASE_DIR}/lib/Qt5Python37.lib -DPYTHONQT_QTALL_INCLUDE_DIR=${PYTHONQT_BASE_DIR}/extensions/PythonQt_QtAll -DPYTHONQT_QTALL_LIBRARY=${PYTHONQT_BASE_DIR}/lib/Qt5Python37_QtAll.lib;
      cmake --build .. --config $CMAKE_BUILD_TYPE; 
    fi

after_success:
  - export VERSION=$TRAVIS_TAG
  - if [ -z "$VERSION" ]; then
      export VERSION=$(git rev-parse --short HEAD);
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        mkdir appdir;
        make install DESTDIR=appdir;
        sudo mkdir -p appdir/usr/lib/python3.4;
        sudo cp -r /usr/lib/python3.4/* appdir/usr/lib/python3.4/;
        sudo mkdir -p appdir/usr/lib/python3/dist-packages/Crypto;
        sudo cp -r /usr/lib/python3/dist-packages/Crypto/* appdir/usr/lib/python3/dist-packages/Crypto/;
        sudo chown -R $(id -nu) appdir;
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
        wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage";
        chmod a+x appimagetool-x86_64.AppImage;
        unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs;
        unlink appdir/AppRun;
        cp ../res/screencloud.sh appdir/AppRun;
        rm -r appdir/usr/plugins/bearer;
        rm -r appdir/usr/plugins/mediaservice;
        rm -r appdir/usr/plugins/platforminputcontexts;
        rm -r appdir/usr/plugins/printsupport;
        rm -r appdir/usr/plugins/sqldrivers;
        rm -r appdir/usr/plugins/xcbglintegrations;
        ./appimagetool-x86_64.AppImage appdir;
        mkdir .snapcraft;
        mkdir snap;
        cp ../deploy/linux/snapcraft.yaml snap/snapcraft.yaml;
        openssl aes-256-cbc -K $encrypted_a38449865927_key -iv $encrypted_a38449865927_iv -in ../.snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d;
        docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq && cd $(pwd) && snapcraft";
        export DEPLOYPATH=$(pwd);
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        sudo make install;
        sudo macdeployqt screencloud.app -verbose=3;
        sudo chown -R $(id -nu) screencloud.app;
        mkdir -p dmgdir/ScreenCloud.app;
        cp -r screencloud.app/* dmgdir/ScreenCloud.app/;
        ln -s /Applications dmgdir/Applications;
        hdiutil create -volname ScreenCloud-$VERSION -srcfolder dmgdir -ov -format UDZO ScreenCloud-$VERSION.dmg;
        export DEPLOYPATH=$(pwd);
    fi

deploy:
  provider: releases
  api_key:
    secure: xY0hOHsO6oztTs/fyKAl4FrA+6ylke3QXsAHzntIEHOt7sgVGQW/4QzJQYPwmAQAkVOssjZWdaJrFXQMFw+lYUpwZGSycPB+fDnosKYlxXFHG4rIliyG+az6ODzA0YeugFwlYAcHXx1qzBJ8gh3tHhB16ur7OQ62VdunCpG7NDtaINGMojzL4DmSfyiyOMPM4p6EcD+qaKd6dxBePXkmZ5J+YOvgfLcd1mJ94V7+WnQ66KltIaFZPewaansw/p6KAUxPXcTMyMepjcjQFQyucs4rN+9EmAaA5d0rzaucbTra1nJbJel0qWC+hcH8WF86ez8nTPFY1MGjRPZmfFGesvwUkzc3IH2w5j82BmP5x7IP+TZQ4qddM/eeWIX4WeTUKoVHHt/+iZNe6kZ7Qv8ZEzQS8/G0WHz0AyoWCKSztMFBs2XZvLPjEjhCr1HKH8ueX2zXFVRf9mpp23kjGyLzacTzSC+6xjrcp27s/fY+NH3kXw67c2tB815BqtYvWMoEZVNF1+7v0nbBOs6SaDAErLqRKOP4GKgEG+J3GvokuVmQpSzwk+v4EX4ixJm3pI6C+yFaDRc7CEtkXRFIPxesMeP2w8thIuWWNaNzRAKlxR4Dx9h4bLunsx5HDfwA9h0CszcOU2ewvrR60QExZ7fjTrIoqC/UWwjoCqFv+TlyGLU=
  file_glob: true
  file: $DEPLOYPATH/*.{dmg,snap,AppImage}
  skip_cleanup: true
  on:
    repo: olav-st/screencloud
    tags: true
