name: screencloud
version: "1.4.0"
summary: Easy to use screenshot sharing application
description: Take a screenshot using one of the 3 hotkeys or simply click the ScreenCloud tray icon. Save your screenshot locally or upload it to the cloud! A link is automatically copied to your clipboard. 
confinement: strict
grade: stable
base: core18

apps:
  screencloud:
    command: desktop-launch screencloud.sh
    desktop: usr/share/applications/screencloud.desktop
    passthrough:
      autostart: screencloud.desktop
    plugs: 
      - x11
      - wayland
      - network
      - home
      - opengl
      - pulseaudio
      - desktop
      - gsettings
      - network-bind #A local port is used to check if another screencloud process is running 
      - network-manager #To get proxy settings
      - unity7

parts:
  screencloud:
    source: https://github.com/olav-st/screencloud.git
    source-tag: master
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - g++
      - qtbase5-private-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - qtmultimedia5-dev
      - qttools5-dev
      - python3-dev
      - libpythonqt-qt5-python3-dev
      - libpythonqt-qtall-qt5-python3-dev
    stage-packages:
      - openssl
      - libqt5concurrent5
      - libqt5x11extras5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libglib2.0-bin
      - libpythonqt-qt5-python3-3
      - libpythonqt-qtall-qt5-python3-3
      - libpython3-stdlib
      - python3-crypto # For the SFTP plugin
      - python3-cryptography # For the SFTP plugin
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=screencloud|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/screencloud.svg|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/screencloud.desktop
    after: [desktop-qt5, quazip]

  quazip:
    source: https://github.com/stachenov/quazip.git
    source-commit: 3d69581
    plugin: qmake
    build-packages:
      - g++
      - zlib1g-dev
      - qtbase5-dev
    stage-packages:
      - zlib1g
      - libqt5core5a
  
  # The desktop-qt5 part must be included manually when using core18 base
  # See: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5
